packages:
  - apps/*
  - packages/*
  - tools/*
allowBuilds:
  aws-sdk: true
  better-sqlite3: true
  esbuild: true
  sharp: true
  sqlite3: true
  workerd: true

catalog:
  "@changesets/cli": ^2.31.0
  "@types/node": ^24
  tsdown: ^0.21.10
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitepress: ^1.6.4
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  wrangler: ^4.88.0

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
