packages:
  - apps/*
  - packages/*
  - tools/*
allowBuilds:
  aws-sdk: true
  better-sqlite3: true
  esbuild: true
  node-rdkafka: true
  protobufjs: true
  sharp: true
  sqlite3: true
  workerd: true

catalog:
  "@changesets/cli": ^3.0.2
  "@types/node": ^24
  "@typescript/native-preview": 7.0.0-dev.20260707.2
  bumpp: ^12.3.0
  tsdown: ^0.23.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@0.3.0
  vite-plus: 0.3.0
  vitepress: ^1.6.4
  wrangler: ^4.129.0

catalogMode: prefer
overrides:
  "vite@*": "catalog:"
  "vitest@*": 4.1.11

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
